site_name: "continuity"
site_dir: "docs_build"
site_url: "https://aai-institute.github.io/continuity/"
repo_name: "aai-institute/continuity"
repo_url: "https://github.com/aai-institute/continuity"
copyright: "Copyright &copy; appliedAI Institute for Europe gGmbH"
remote_branch: gh-pages

theme:
  name: mkdocs
  custom_dir: overrides
